name: dds-dev
services:
  frontend:
    image: node:20
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    #      - /app/node_modules
    #    develop:
    #      watch:
    #        - action: sync
    #          path: ./frontend
    #          target: /frontend/src
    #          ignore:
    #            - node_modules/
    #        - action: rebuild
    #          path: package.json
    ports:
      - 3000:3000
    networks:
      - dds-dev-net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - NODE_ENV=development

  backend:
    build: .
    working_dir: /app
    ports:
      - 4000:4000
      - 4444:4444
    volumes:
      - ./ddsurveys:/app/ddsurveys
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dds-dev-net
    environment:
      - DDS_ENV=development

  db:
    image: mariadb:latest
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dds
    networks:
      - dds-dev-net
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 3s
      retries: 5

networks:
  dds-dev-net:
    name: dds-dev-net
