name: dds-deploy
services:
  backend:
    build: .
    image: dds:backend
    restart: on-failure
    volumes:
      - ./ddsurveys:/app/ddsurveys
    ports:
      - "4000:4000" # to be removed
    expose:
      - "4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
    environment:
      - DDS_ENV=production
      - BACKEND_SERVICE_NAME=backend

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: dds:frontend
    restart: on-failure
    volumes:
      - ./frontend:/app/
      - ./volumes/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/letsencrypt
      - ./volumes/self-signed-ssl:/etc/self-signed-ssl
      - ./volumes/nginx/nginx-entrypoint.sh:/nginx-entrypoint.sh
      - ./.env.deploy.local:/.env.deploy.local
    ports:
      - "443:443"
      - "80:80"
    # entrypoint: "sleep 10m; /nginx-entrypoint.sh"
    entrypoint: "/nginx-entrypoint.sh"
    depends_on:
      - backend
      - certbot
    networks:
      - net
    environment:
      - NODE_ENV=production
      - DDS_ENV=production
      - BACKEND_SERVICE_NAME=backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/letsencrypt
      - ./volumes/certbot/certbot-entrypoint.sh:/certbot-entrypoint.sh
      - ./volumes/self-signed-ssl:/etc/self-signed-ssl
      - ./.env.deploy.local:/.env.deploy.local
    entrypoint: "/certbot-entrypoint.sh"
    networks:
      - net

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dds
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 5

networks:
  net:
    external: false
