name: dds-build
services:
  frontend:
    image: node:20
    working_dir: /app
    command: bash -c "npm run serve-build"
#    command: bash -c "sleep 1000"
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - dds-build-net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
      - NODE_ENV=development

networks:
  dds-build-net:
    name: dds-build-net
