name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_ddsurveys_tests:
    name: Run ddsurveys pytest tests
    runs-on: ubuntu-latest
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python environment
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      # Install dependencies
      - name: Install the project
        run: uv sync --all-extras --dev

      # Run tests
      - name: Run tests
        run: uv run pytest tests -v

      # Prune cache
      - name: Minimize uv cache
        run: uv cache prune --ci
